### ISSUE TITLE
Mass assignment

### ISSUE THREAD

**Issue by graymic** [cerbero90/Workflow#2]
Is it possible to use mass assignment within the command bus using your workflow?

**Comment by cerbero90** [comment]
Hi @graymic :)

not sure I understand, mass assignment is an issue of models rather than command bus.

If you mean if it's possible to create/update database entries within workflows, then yes it's definitely possible :)

**Comment by graymic** [comment]
Yep that's what I was referring to @cerbero90 thanks! :)

**Comment by cerbero90** [comment]
No worries, thanks for your interest in this project :)
